type: m
manager:
  address: 35.200.83.50:6002
  password: '123456'
plugins:
  flowSaver:
    use: true
  user:
    use: true
  account:
    use: true
  email:
    use: true
    type: 'mailgun'
    baseUrl: 'https://api.mailgun.net/v3/sandbox4ea98cd23b274a06a3361f9d918cf584.mailgun.org'
    apiKey: '56300a25f8a481378c5f9a9a87b72387-e566273b-ac148a04'
  webgui:
    use: true
    host: '0.0.0.0'
    port: '80'
    site: 'http://127.0.0.1'
    # icon: 'icon.png'
    # skin: ''
    # googleAnalytics: 'UA-xxxxxxxx-x'
    # gcmSenderId: '476902381496'
    # gcmAPIKey: 'AAAAGzddLRc:XXXXXXXXXXXXXX'
  alipay:
    use: true
    appid: 2019050764393134
    notifyUrl: 'http://35.185.149.28/api/user/alipay/callback'
    merchantPrivateKey: 'MIIEowIBAAKCAQEAw9RiWq4v5KJgzkJJtYemCj9x1HmTTDEUeuo458sxYTyKzd3etpeiUcvuE/B+XgmhzfxUnRLmgRZLmzXJnh3VjZlc5t/0ZaBp8DAimLxmAcRGfclnIx+AkLKxas5FYcbpx4CMcsnnZ7D50t8Zbs+gEXcDwvsYI/cnCir5qHoW42wwnGulJlRQyABeJ2SzrTX6xqqBTViJeyILiCQmbwd50zGv91TpyggRL2s0XnsCukcjo28CfbWkEbCShMEMP5Zhd9RPvUBzIBtsySNIHRJ/77us6+lR8QSeQMYgBltf1LY+T7vagUO+GZ9trd23eIqC6hHocfJJ15RdZgNkinIJsQIDAQABAoIBADi/44DD2b04ETW0oAerN8Lgf+xDDxyVXIoCNlt11umG0fK2yUPAzZlGr8e3eedmgy1eYmbig0oFXAOuoq7flnNibjm5zOlmg0zHpj782dLJPmRVaT4Ucv17y05YWGLtcfIOnqTlPdoev0cMwCIMqSZmhwCKI4TIqteXfKIGP3vH69uKSbmx7d3aVw068aWl/XWvwmVkbBJvJtvslaEtRrUkcDoAj4gSBjI3Ude5MSUE0uszi8wW9HeIPs/fN4XU1Jfo5F6/jZrkPeokBQSh4sRLEiy4lL1YpG46olrV07qC4gLkyhfGmlrobkDigBdVAWddw/e8mc0Qh7oeycrH6sECgYEA/E/69Ci40UtR5vR3+dM6DV5UtjFlt/rqvi1WIaAHLp7dPjQMHuD2mDintns/TFJdkNjS8rDpDHt/DeNVLD/Pp+hlbC+SBrc14Qi8TNJyDb3oQZRCyOVHjfsTigIhDKzxmXm7wvMS8RNI8zKkrtfVobXquNbltrB/MjWvNBWbKq8CgYEAxrETPEJ28qhaEphDOYUfeJKk1dK+m0Z7HOU35EXLx5z+wEmi0GbIYkLttVPhOjRJcH/mltBtsJ/xYO+FOW8ca79YgmYpMFAR2uyWp+0mD8QUP6wMT9A/vEi6xgmCYLzsKIhEf/xjdF03FTTnf1RKb89yTUs+X7FnRjg4h+OrqZ8CgYBAAkJWAqawYf1LLCXruQx3K8Et32ZAwGUhDftV2HU5/I+AIlAY3VVx1J2ni6jJQfP+tSL+8qaMxh+7dDq9WQrjO+/O/Fp9XalLh53Nl23b0pvDV0uCD7iRamrQji24O3+nQdzCXkwl4JCXMffZa2QE/FOpxMrOCAScxkXGXtzYfQKBgFVxmrsEPhC2Ex4B+o7Gz7TTIy2MlklB8vmHHRT+atapjef1Ap4qRSv0ajLbInUcPSSy69+ZPEKDVZMBDcKYJJm1TIOvGTFcjYEe0t7eHcsT4D1NaHH+NRpsEF3PgxDEza3Ug9iiGcbVuzVUbeUUw3n3tMjGfck7ChVpYe4WGyEzAoGBAMhsHkxZPuVqzAufxkgoqxTQZNb72bINdAxnGRQApgStp3Of/vTHZMB7q/riA+iLw+jJXIHa6wXvl/Q4q+Ts/RxSBYs2EKKfeSd5QM9Xnpb8sXHewIUCvOZmI5LvQqCqXuSSBsnOhMiu8j7BLEw+Ha0vlA2LNGmPgxIAEyH0LuMT'
    alipayPublicKey: 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkSmL7Wp5gozyfIHosl9XsslidfAgzfhje3X/8nd9okyvsKPNfumbWQ0kcGyINnDWcDNGAwMhLrIc1We5EhdWL1Ngt8TOOj9VWKIpr5eH772cYv4PdjxvXbQBqnsImmKGgZfd4KZ36c2Z/Kq+X32i5ybunejl/yIdcK/rjgRdRHp4tkJuQf9+uC9yBHn5R+uq9Ryg5hS+d0EplqLkw9MDHswyEWEZRIXqz6RC5MceAuqpy4HBgDVoCUrwT12uSCn2Df7nLX++dyg4t7V2meDv4uZNozua/V/XhnjJ5YC9QyG5jb5NXvmDD3CO2vrrwdm70/PUUQBYexOmOHLKQTGFJQIDAQAB'
    gatewayUrl: 'https://openapi.alipay.com/gateway.do'
db: 'webgui.sqlite'
# 从 0.30 开始需要配置 redis
redis:
  host: '127.0.0.1'
  port: 6379
  password: ''
  db: 0